account/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login,logout
from . import views

app_name = 'account'
urlpatterns = [
        url(r'^login/$', login, {'template_name': 'login.html'} ,name='login'),
        url(r'^logout/$', logout, {'template_name':'logout.html'}, name='logout'),
        url(r'^register/$', views.register, name='register'),
        url(r'^user_list/$', views.UserList.as_view(), name='user_list'),
        url(r'^$', views.ahome, name='home'),
        url(r'^login/$', login, {'template_name': 'login.html'} ,name='login'),
        url(r'^logout/$', logout, {'template_name':'logout.html'}, name='logout'),
        url(r'^register/$', views.register, name='register'),
        url(r'^userlist/$', views.UserList.as_view(), name='userlist'),
        url(r'^profile/$', views.profile, name='profile'),
        url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
        url(r'^(?P<id>\d+)/',views.deleteprofile, name='delete'),
        url(r'^profile/changepassword/$', views.changepassword, name='change_password'),
        url(r'^profile/(?P<id>\d+)/',views.userdetail, name='user_detail'),


]

bucky/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^home/',include('home.urls')),
    url(r'^account/', include('account.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url
from home.views import HomeView

app_name = 'home'

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),


]

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager,self).get_queryset().filter(city='Hisar')

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    discription = models.CharField(max_length=100, default='')
    city = models.CharField(default='',max_length=100)
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.FileField(null=True,blank=True)

    def __str__(self):
        return self.user.username

    Hisar = UserProfileManager()

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    post = models.CharField(max_length=500)
    user = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.post[:9]

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile
class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)


    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',



        ]

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

home/forms.py
from django import forms
from .models import Post
class homeForm(forms.ModelForm):
    post = forms.CharField()
    class Meta:
        model = Post
        fields = ['post']

account/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import RegistrationForm
from django.contrib.auth.models import User
from .models import UserProfile
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.views.generic import ListView,DetailView,DeleteView
from django.views.generic import TemplateView
# Create your views here.
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView,DetailView,DeleteView
# Create your views here.

def ahome(request):
    context={}
    template = 'ahome.html'
    return render(request, template, context)

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect('account:user_list')

    else:
        form = RegistrationForm()
        args = {'form':form}
        return render(request, 'reg_form.html', args)

# class-based user list to find friends
class UserList(ListView):
    template_name = 'user_list.html'
    context_object_name = 'r'

    def get_queryset(self):
        return User.objects.all()

# to delete user-profil



'''def userlist(request):
    user = User.objects.all()
    query = request.GET.get('q')
    if query:
        user = user.filter(
            Q(city__icontains=query)
        ).distunct()
    context = {'users':user}
    template = 'user_list.html'
    return render(request,template,context)
'''
@login_required
def userdetail(request,id=None):
    instance = get_object_or_404(User, id=id)
    context = {'r':instance}
    template = 'user_detail.html'
    return render(request,template,context)

@login_required
def profile(request):
    context = {'user':request.user}
    template = 'profile.html'
    return render(request,template,context)



@login_required
def edit_profile(request):
    if request.method == "POST":
        form = UserChangeForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('account:profile')
    else:
        form = UserChangeForm(instance=request.user)
        context = {'form':form}
        template = 'edit_profile.html'
        return render(request,template,context)

@login_required
def changepassword(request):
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/account/profile')
    else:
        form = PasswordChangeForm(user=request.user)
        context = {'form':form}
        template = 'change_password.html'
        return render(request,template,context)


@login_required
def deleteprofile(request,id = None):
    dal = get_object_or_404(User, id = id)
    dal.delete()
    context = {'msg':"Account Successfully deleted."}
    return render(request,'logout.html',context)

home/views.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView
from .forms import homeForm
from .models import Post

# Create your views here.
class HomeView(TemplateView):
    template_name = 'home.html'

    def get(self, request, *args, **kwargs):
        form = homeForm()
        posts = Post.objects.all().order_by('created')
        context = {'form':form,'posts':posts}
        return render(request,self.template_name,context)

    def post(self,request):
        form = homeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            text = form.cleaned_data['post']
            form = homeForm()
            return redirect('home:home')

        context = {'form':form, 'text':text}
        return render(request,self.template_name,context)

account/templates/ahome.html
{% extends 'base.html' %}
{% block head %}<title>Account homepage</title>{% endblock %}
{% block content %}
<h3 class="text-center">Welcome to My Network</h3>
<p class="text-center">Please Login or Register to use our service</p>

{% endblock %}

account/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head %}<title>Title</title>{% endblock %}
     {% load staticfiles %}
    <meta charset="UTF-8">
    <!-- Latest compiled and minified CSS -->
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
<div class="container">
<h2>My Network</h2>
<ol class="breadcrumb">
    <li><a href="{% url 'home:home' %}">Home</a></li>
    {% if not request.user.is_authenticated %}
    <li class="pull-right"><a href="{% url 'account:register' %}">Register</a></li>
    <li class = 'pull-right'><a href="{% url 'account:login' %}">Login</a></li>

    {% else %}
    <li><a href="{% url 'account:user_list' %}">Find Friend</a></li>
    <li class="pull-right"><a href="{% url 'account:logout' %}">Logout</a></li> /
    <li class="pull-right"><a href="{% url 'account:profile' %}">My Profile</a></li>
    {% endif %}
</ol>






{% block content %}


{% endblock %}
    </div>
</body>
</html>

account/templates/change_password.html
{% extends 'base.html' %}
{% block head %}<title>Account homepage</title>{% endblock %}
{% block content %}
<form method="post">
    {% load crispy_forms_tags %}
    {% csrf_token %}
    {{ form | crispy }}
    <button type="submit" class="btn btn-success">Change Password</button>

</form>
{% endblock %}

account/templates/edit_profile.html
{% extends 'base.html' %}
{% block head %}<title>Account homepage</title>{% endblock %}
{% block content %}
<form method="post">
    {% load crispy_forms_tags %}
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit">Update</button>
</form>
{% endblock %}

account/templates/login.html
{% extends 'base.html' %}
{% block head %}<title>Login Here</title>{% endblock %}
{% block content %}
<h3>You can log in here.</h3>
<form method="post">
    {% csrf_token %}
    {% load crispy_forms_tags %}
    {{form | crispy}}
    <br>
    <button type="submit">Login</button>
</form>

{% endblock %}

account/templates/logout.html
{% extends 'base.html' %}
{% block head %}<title>Logout!</title>{% endblock %}
{% block content %}

<h3>You are successfully logged out!</h3>
<p>You can <a href="{% url 'account:login' %}">login here</a></p>

<h3>{{msg}}</h3>
<p>You can <a href="{% url 'account:register' %}">register here</a></p>

{% endblock %}

account/templates/profile.html
{% extends 'base.html' %}

{% block head %}<title>Account homepage</title>{% endblock %}

{% block content %}

    <p class="pull-right row">
        Welcome
        <a href="{% url 'account:profile' %}">{{user}}</a> /
        <a href="{% url 'account:edit_profile' %}">Edit Profile</a> /
        <a href="{% url 'account:change_password' %}">Change Password</a> /
        <a href="{% url 'account:delete' user.id %}">Delete Profile</a>
    </p>
    <div class="col-md-4">
    <h4>Profile</h4>
    {% if user.userprofile.image %}
    <img src="{{user.userprofile.image.url}}" class="img-responsive" height="200px" width="200px"/>
    {%endif%}
    <p>Username: {{user.username}}</p>
    <p>Name: {{user.first_name}} {{user.last_name}}</p>
    <p>E-mail: {{user.email}}</p>
    <p>About: {{user.userprofile.discription}}</p>
    <p>City: {{user.userprofile.city}}</p>
    <p>Website: <a href="{{user.userprofile.website}}" target="_blank">{{user.userprofile.website}}</a></p>
    <p>Mobile: {{user.userprofile.phone}}</p>


</div>
{% endblock %}

account/templates/reg_form.html
{% extends 'base.html' %}
{% block head %}<title>User registration</title>{% endblock %}
{% block content %}
<h3>User can register Here</h3>
<form method="post">
    {% load crispy_forms_tags %}
    {% csrf_token %}
    {{ form|crispy}}
     <button type="submit">Submit</button>
</form>

{% endblock %}

account/templates/user_confirm_delete.html
<form action="" method="post">
    {% csrf_token %}
    <p>Do you really want to delete this song</p>
    <input type="submit" value="Confirm">
</form>

account/templates/user_detail.html
{% extends 'base.html' %}

{% block head %}<title>{{user}}</title>{% endblock %}

{% block content %}
<div class="col-md-4">
    <p class="pull-right">
        Welcome
        <a href="{% url 'account:profile' %}">{{user}}</a> /
        <a href="{% url 'account:edit_profile' %}">Edit Profile</a> /
        <a href="{% url 'account:change_password' %}">Change Password</a>
    </p>
    <h4>Profile</h4>
    {% if r.userprofile.image %}
    <img src="{{r.userprofile.image.url}}" class="img-responsive" height="200px" width="200px"/>
    {% endif %}
    <p>Username: {{r.username}}</p>
    <p>First Name: {{r.first_name}}</p>
    <p>Last Name: {{r.last_name}}</p>
    <p>E-mail: {{r.email}}</p>
    <p>About: {{r.userprofile.discription}}</p>
    <p>City: {{r.userprofile.city}}</p>
    <p>Website: <a href="{{r.userprofile.website}}" target="_blank">{{r.userprofile.website}}</a></p>
    <p>Mobile: {{r.userprofile.phone}}</p>


</div>
{% endblock %}

account/templates/user_list.html
{% extends 'base.html' %}
{% block head %}<title>User List</title>{% endblock %}
{% block content %}
{% if request.user.is_authenticated %}
<p class="pull-right">
        Welcome
        <a href="{% url 'account:profile' %}">{{user}}</a> /
        <a href="{% url 'account:edit_profile' %}">Edit Profile</a> /
        <a href="{% url 'account:change_password' %}">Change Password</a>
    </p>{% endif %}
<h3 class="text-center">Find Friends</h3><hr>
<form method="get" action="" class="pull-right">

        <input type="text" name="q" value="{{request.GET.q}}" placeholder="Find Friends" required>
        <input type="submit" value="Search" class="btn btn-success">
    </form>

{% for user in r %}
<div class="row" style="margin-top:50px;">

    <div class="col-md-2">
    {% if user.userprofile.image %}
    <img src="{{user.userprofile.image.url}}" height="130px" width="150px"/>
        {% endif %}</div>
    <div class="col-md-4">
    <p>{{user.first_name}} {{user.last_name}}</p>
    <p>{{user.userprofile.city}}</p>
        <a href="{% url 'account:user_detail' user.id %}">Add Friends</a>
</div>
</div>
{% endfor %}
{% endblock %}

home/templates/home.html
{% extends 'base.html' %}
{% block content  %}
<h2>Its working</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Post!</button>

</form>

<p>You just posted: <b>{{text}}</b></p>
{% for post in posts %}
    <h1>{{post.post}}</h1>
    <p>Posted by: {{post.user.get_full_name}} on {{post.created}}</p>
{% endfor %}
{% endblock %}